version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "schedule"
      POSTGRES_USER: "pryabykh"
      POSTGRES_PASSWORD: "pryabykh"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres: